/**
 * Benchmark of the backend: reads, filters, writes, import map, export, the json file flush and the REST layer, on a
 * seeded store of 10k and 100k records (several field types, localised fields, image attachments).
 * Not part of the test run. Usage:
 *
 *   node --expose-gc test/bench/bench.js [--sizes 10000,100000] [--only list,filter,...] [--json out.json]
 *
 * Every number is milliseconds per operation unless the name says otherwise. The data is generated by a seeded
 * generator, so two runs measure the same store.
 */
const fs = require('fs')
const http = require('http')
const os = require('os')
const path = require('path')
const { performance, monitorEventLoopDelay } = require('perf_hooks')

process.env.LOG_LEVEL = process.env.LOG_LEVEL || 'error'
const { startApp, randomSecret } = require('../helpers/app')
const sanitizeQuery = require('../../lib/util/sanitizeQuery')

const args = process.argv.slice(2)
const option = (name, fallback) => {
  const index = args.indexOf(`--${name}`)
  return index >= 0 ? args[index + 1] : fallback
}
const SIZES = option('sizes', '10000,100000') === 'none' ? [] : option('sizes', '10000,100000').split(',').map(Number)
const ONLY = option('only', '') ? option('only').split(',') : null
const OUTPUT = option('json')
const wanted = (name) => !ONLY || ONLY.includes(name)

// mulberry32: small seeded generator
const random = (seed) => () => {
  seed |= 0
  seed = seed + 0x6D2B79F5 | 0
  let t = Math.imul(seed ^ seed >>> 15, 1 | seed)
  t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t
  return ((t ^ t >>> 14) >>> 0) / 4294967296
}
const WORDS = ['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 'India', 'Juliet', 'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa', 'Quebec', 'Romeo', 'Sierra', 'Tango']

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms))
const gc = () => global.gc && global.gc()
const mb = (bytes) => Math.round(bytes / 1024 / 1024 * 10) / 10

/**
 * Runs a function `times` times and reports the mean time per run.
 * @param {function(number): Promise<*>} fn
 * @param {number} times
 * @returns {Promise<{ms: number, times: number}>}
 */
async function time (fn, times = 1) {
  const started = performance.now()
  for (let i = 0; i < times; i++) {
    await fn(i)
  }
  return { ms: Math.round((performance.now() - started) / times * 1000) / 1000, times }
}

function makeRecord (index, next, uuid, now) {
  const words = () => `${WORDS[Math.floor(next() * WORDS.length)]} ${WORDS[Math.floor(next() * WORDS.length)]} ${Math.floor(next() * 1000)}`
  const id = uuid()
  const attachments = []
  const count = Math.floor(next() * 4)
  for (let i = 0; i < count; i++) {
    attachments.push({
      _id: uuid(),
      _createdAt: now,
      _updatedAt: now,
      _name: 'photo',
      _contentType: 'image/jpeg',
      _md5sum: Math.floor(next() * 1e16).toString(16).padStart(32, '0'),
      _payload: {},
      _size: 10000 + Math.floor(next() * 500000),
      _filename: `photo-${index}-${i}.jpg`,
      _fields: {},
      _meta: { width: 1200, height: 800 }
    })
  }
  return {
    _id: id,
    _createdAt: now,
    _updatedAt: now,
    _publishedAt: null,
    sku: `SKU-${String(index).padStart(7, '0')}`,
    name: { enUS: words(), zhCN: words() },
    description: { enUS: `${words()} ${words()} ${words()} ${words()}`, zhCN: `${words()} ${words()}` },
    price: Math.round(next() * 10000) / 100,
    stock: Math.floor(next() * 500),
    active: next() > 0.2,
    category: `category-${Math.floor(next() * 20)}`,
    released: new Date(1500000000000 + Math.floor(next() * 3e10)).toISOString(),
    _attachments: attachments
  }
}

/**
 * Writes N seeded records straight into the store, in batches (through the same prewrite hooks as any write).
 */
async function seed (app, size) {
  const resource = app.cms.resource('products')
  const next = random(size)
  const uuid = app.cms.options.uuid
  const now = 1700000000000
  for (let from = 0; from < size; from += 5000) {
    const operations = []
    for (let i = from; i < Math.min(size, from + 5000); i++) {
      operations.push({ type: 'put', key: undefined, value: undefined })
      const record = makeRecord(i, next, uuid, now + i)
      operations[operations.length - 1] = { type: 'put', key: record._id, value: record }
    }
    await resource.json._db.batch(operations)
  }
  // let the debounced flush of the file happen before measuring
  await sleep(200)
  await resource.json._db._persist()
}

function samplePeakRss (interval = 25) {
  let peak = process.memoryUsage().rss
  const timer = setInterval(() => { peak = Math.max(peak, process.memoryUsage().rss) }, interval)
  return () => { clearInterval(timer); return peak }
}

// a new connection for every request: a busy server closes the idle keep-alive ones of a client that waits for it
const request = (url, headers) => new Promise((resolve, reject) => {
  http.get(url, { headers: { ...headers, Connection: 'close' }, agent: false }, (res) => {
    let bytes = 0
    res.on('data', chunk => { bytes += chunk.length })
    res.on('end', () => resolve({ status: res.statusCode, bytes }))
  }).on('error', reject)
})

async function runSize (size, results) {
  const started = performance.now()
  const app = await startApp({ resources: './test/bench/resources', smartCrop: false, xlsx: true }, { keepData: true })
  const out = {}
  results[size] = out
  try {
    gc()
    const baseline = process.memoryUsage().heapUsed
    await seed(app, size)
    const api = app.cms.api()
    const products = api('products')
    const notes = api('notes')
    const file = path.join(app.dataDir, 'products', 'json', 'db.json')
    out.seedMs = Math.round(performance.now() - started)
    out.dbFileMb = mb(fs.statSync(file).size)
    gc()
    out.heapAfterSeedMb = mb(process.memoryUsage().heapUsed - baseline)

    if (wanted('list')) {
      out.list_all = await time(() => products.list(), size > 50000 ? 3 : 10)
      out.list_page = await time(() => products.list({}, { page: 2, limit: 50 }), 20)
      out.read_first_50 = await time(() => app.cms.resource('products').read({}, { limit: 50 }), 20)
    }
    if (wanted('find')) {
      const ids = (await products.list({}, { limit: 1000 })).map(item => item._id)
      out.find_by_id = await time((i) => products.find(ids[i % ids.length]), 1000)
      out.find_unique = await time((i) => products.find({ sku: `SKU-${String((i * 7919) % size).padStart(7, '0')}` }), size > 50000 ? 10 : 30)
    }
    if (wanted('filter')) {
      const times = size > 50000 ? 3 : 10
      out.filter_eq = await time(() => products.list({ category: 'category-3' }), times)
      out.filter_regex = await time(() => products.list({ 'name.enUS': { $regex: '^Alpha' } }), times)
      out.filter_range = await time(() => products.list({ price: { $gte: 10, $lt: 12 } }), times)
      out.filter_in = await time(() => products.list({ category: { $in: ['category-1', 'category-2'] } }), times)
      out.filter_paged = await time(() => products.list({ category: 'category-3' }, { page: 2, limit: 50 }), times)
    }
    if (wanted('write')) {
      const times = size > 50000 ? 20 : 100
      out.create_unique = await time((i) => products.create({ sku: `NEW-${i}`, name: { enUS: `New ${i}` }, price: i }), times)
      out.create_plain = await time((i) => notes.create({ title: `note ${i}`, body: 'x' }), times)
      const created = await products.list({ sku: { $regex: '^NEW-' } })
      out.update_unique = await time((i) => products.update(created[i % created.length]._id, { stock: i }), times)
      out.remove = await time((i) => products.remove(created[i % created.length]._id).catch(() => {}), Math.min(times, created.length))
      // a burst: what a script that creates records in a loop sees
      // creates spread over a few seconds, while the event loop is watched: the flush of the file blocks it
      const histogram = monitorEventLoopDelay({ resolution: 5 })
      histogram.enable()
      out.create_burst_300 = await time(async (i) => { await notes.create({ title: `burst ${i}`, body: 'y' }); await sleep(8) }, 300)
      histogram.disable()
      out.create_burst_300.eventLoopMaxMs = Math.round(histogram.max / 1e6)
      out.create_burst_300.eventLoopP99Ms = Math.round(histogram.percentile(99) / 1e6)
    }
    if (wanted('flush')) {
      const db = app.cms.resource('products').json._db
      db._dirty = true
      out.flush = await time(async () => { db._dirty = true; await db._persist() }, 3)
    }
    if (wanted('import')) {
      const sample = (await products.list({}, { limit: 2000 })).map(item => ({ sku: item.sku, name: item.name, price: item.price + 1, stock: item.stock, category: item.category }))
      out.import_map_2000 = await time(() => products.getImportMap(sample.map(item => ({ ...item }))), 1)
    }
    if (wanted('export') && size <= 10000) {
      await app.cms.api()('_xlsx').create({ token: 'bench' })
      const stop = samplePeakRss()
      gc()
      const before = process.memoryUsage().rss
      let answer
      out.xlsx_export = await time(async () => { answer = await request(`${app.url}/xlsx/products?token=bench`) }, 1)
      out.xlsx_export.peakRssDeltaMb = mb(stop() - before)
      out.xlsx_export.status = answer.status
      out.xlsx_export.fileMb = mb(answer.bytes)
    }
    if (wanted('sanitize')) {
      const queries = [{ category: 'x' }, { price: { $gte: 1, $lt: 2 } }, { $or: [{ 'name.enUS': { $regex: '^a' } }, { active: true }] }]
      const started2 = performance.now()
      for (let i = 0; i < 100000; i++) {
        sanitizeQuery(queries[i % 3], { safeRegex: true })
      }
      out.sanitize_query_us = Math.round((performance.now() - started2) / 100000 * 1000 * 1000) / 1000
    }
    if (wanted('rest')) {
      const auth = { Authorization: `Basic ${Buffer.from('localAdmin:localAdmin').toString('base64')}` }
      const times = size > 50000 ? 24 : 240
      const hammer = async (path) => {
        const started = performance.now()
        let last
        await Promise.all(Array.from({ length: 8 }, async () => {
          for (let i = 0; i < times / 8; i++) {
            last = await request(`${app.url}${path}`, auth)
          }
        }))
        return { reqPerSecond: Math.round(times / ((performance.now() - started) / 1000) * 10) / 10, status: last.status, responseKb: Math.round(last.bytes / 1024) }
      }
      out.rest_list_50 = await hammer('/api/products?limit=50')
      out.rest_list_page_3 = await hammer('/api/products?limit=50&page=3')
      out.rest_query_unique = await hammer(`/api/products?query=${encodeURIComponent(JSON.stringify({ sku: 'SKU-0000042' }))}`)
      out.rest_find_by_id = await hammer(`/api/products/${(await products.list({}, { limit: 1 }))[0]._id}`)
    }
  } finally {
    await app.close()
  }
  // reopening: parse the file and build the store
  if (wanted('open')) {
    const started3 = performance.now()
    const again = await startApp({ resources: './test/bench/resources', smartCrop: false }, { dataDir: app.dataDir })
    out.boot_ms = Math.round(performance.now() - started3)
    await again.close()
  } else {
    fs.rmSync(app.dataDir, { recursive: true, force: true })
  }
  return out
}

async function runScrypt (results) {
  // Basic authentication verifies the password on every request: what a memory hard hash costs there
  const out = {}
  results.basicAuth = out
  const secret = () => ({ auth: { secret: randomSecret() }, session: { secret: randomSecret() } })
  for (const scheme of ['legacy', 'scrypt']) {
    const app = await startApp({ resources: './test/bench/resources', smartCrop: false, ...secret(), security: { passwordHash: scheme } })
    try {
      const authentication = app.cms.$authentication
      await authentication.users.create({ username: 'bench', password: 'bench-password', group: authentication.adminsGroup._id })
      const auth = { Authorization: `Basic ${Buffer.from('bench:bench-password').toString('base64')}` }
      await request(`${app.url}/api/notes`, auth)
      const times = 120
      const t0 = performance.now()
      await Promise.all(Array.from({ length: 8 }, async () => {
        for (let i = 0; i < times / 8; i++) {
          await request(`${app.url}/api/notes`, auth)
        }
      }))
      out[`${scheme}_req_per_s`] = Math.round(times / ((performance.now() - t0) / 1000))
    } finally {
      await app.close()
    }
  }
}

async function runAttachments (results) {
  // serving one image many times: the request path of an attachment (cache lookups, log lines)
  const logger = require('../../lib/logger')
  const out = {}
  results.attachments = out
  const app = await startApp({ resources: './test/bench/resources', smartCrop: false })
  const auth = { Authorization: `Basic ${Buffer.from('localAdmin:localAdmin').toString('base64')}` }
  try {
    const record = await app.cms.api()('products').create({ sku: 'IMG-1', name: { enUS: 'with image' } })
    const image = fs.readFileSync(path.join(__dirname, '..', 'man.jpg'))
    const form = new FormData()
    form.append('_filename', 'man.jpg')
    form.append('photo', new Blob([image], { type: 'image/jpeg' }), 'man.jpg')
    const uploaded = await fetch(`${app.url}/api/products/${record._id}/attachments`, { method: 'POST', headers: auth, body: form })
    const attachment = await uploaded.json()
    const base = `${app.url}/api/products/${record._id}/attachments/${attachment._id}`
    await request(`${base}?resize=100xauto`, auth)
    let lines = 0
    const originalLog = console.log
    console.log = (...args) => { lines++; originalLog(...args) }
    const previous = logger.level
    logger.level = 'info'
    try {
      const times = 300
      for (const [name, url] of [['original', base], ['resized_cached', `${base}?resize=100xauto`]]) {
        lines = 0
        const started = performance.now()
        await Promise.all(Array.from({ length: 8 }, async () => {
          for (let i = 0; i < times / 8; i++) {
            await request(url, auth)
          }
        }))
        out[name] = { reqPerSecond: Math.round(times / ((performance.now() - started) / 1000)), logLinesPerRequest: Math.round(lines / times * 10) / 10 }
      }
    } finally {
      console.log = originalLog
      logger.level = previous
    }
  } finally {
    await app.close()
  }
}

async function runImages (results) {
  const sharp = require('sharp')
  const ImageOptimization = require('../../lib/util/imageOptimization')
  const { Readable } = require('stream')
  const image = await sharp({ create: { width: 5000, height: 3500, channels: 3, noise: { type: 'gaussian', mean: 128, sigma: 60 } } }).jpeg({ quality: 90 }).toBuffer()
  const out = { sourceMb: mb(image.length) }
  results.images = out
  for (const parallel of [1, 8, 24]) {
    gc()
    const before = process.memoryUsage().rss
    const stop = samplePeakRss(10)
    const started = performance.now()
    await Promise.all(Array.from({ length: parallel }, (_, i) => ImageOptimization.resizeAttachment(Readable.from([image]), `${300 + i}x200`)))
    out[`resize_${parallel}_parallel`] = { totalMs: Math.round(performance.now() - started), peakRssDeltaMb: mb(stop() - before) }
  }
}

async function main () {
  const results = { node: process.version, cpus: os.cpus().length, seed: 'mulberry32', sizes: SIZES }
  for (const size of SIZES) {
    console.error(`--- ${size} records`)
    await runSize(size, results)
    console.error(JSON.stringify(results[size]))
  }
  if (wanted('scrypt')) {
    await runScrypt(results)
  }
  if (wanted('attachments')) {
    await runAttachments(results)
  }
  if (wanted('images')) {
    await runImages(results)
  }
  const text = JSON.stringify(results, null, 2)
  if (OUTPUT) {
    fs.writeFileSync(OUTPUT, text)
  }
  console.log(text)
  process.exit(0)
}

main().catch((error) => { console.error(error); process.exit(1) })
