/**
 * End to end benchmark of the storage engines: the real CMS is started on each engine and driven through its REST API, so the
 * numbers include everything a request goes through (authentication, rights, hooks, unique keys, the store, the answer).
 * Create, read, update, delete, list, find, filter and file upload and download are timed, for one client at a time (the
 * latency of an operation) and for eight at once (what the server holds under load).
 * `stores.js` measures the engines alone, through the key-value interface; `bench.js` measures the CMS on one store.
 * Not part of the test run. Usage:
 *
 *   node --expose-gc test/bench/engines.js [--size 10000] [--engines jsondown,sqlite,leveldb,mongodb,postgres]
 *                                          [--scale 1] [--json out.json] [--markdown out.md]
 *   node test/bench/engines.js --table out.json      (print the table of a saved report again)
 *
 * Every engine runs in a process of its own, so that the memory figures are not mixed. `--scale` multiplies how many times each
 * operation is repeated (0.2 for a quick look, 3 for steadier numbers). MongoDB and PostgreSQL are measured when
 * BENCH_MONGODB_URL (host:port) and BENCH_POSTGRES_URL (host:port, with POSTGRES_USER and POSTGRES_PASSWORD in the environment)
 * are set; each gets a database of its own, dropped afterwards. Every time is milliseconds unless the name says otherwise.
 * The records are generated by a seeded generator, so two runs measure the same store.
 *
 * Disk space is the data folder of the CMS for the local engines (the store and the uploaded files). For the two servers it
 * is what the server holds for the database of the run, plus the uploaded files, which stay in the data folder whatever the
 * engine: MongoDB's storageSize + indexSize from dbStats after an fsync (a checkpoint; before it the figure is the size of
 * the files before the last writes reached them), the sum of pg_total_relation_size over the tables of PostgreSQL (the rows,
 * their TOAST and their indexes, without the catalogs every database carries).
 */
const fs = require('fs')
const os = require('os')
const path = require('path')
const http = require('http')
const crypto = require('crypto')
const { spawn } = require('child_process')
const { performance } = require('perf_hooks')
const { AsyncLocalStorage } = require('async_hooks')

const args = process.argv.slice(2)
const option = (name, fallback) => {
  const index = args.indexOf(`--${name}`)
  return index >= 0 ? args[index + 1] : fallback
}
let SIZE_FROM_REPORT
const SIZE = Number(option('size', '10000'))
const SCALE = Number(option('scale', '1'))
const REMOTE = ['mongodb', 'postgres']
const DEFAULT_ENGINES = ['jsondown', 'sqlite', 'leveldb']
const AUTH = { Authorization: `Basic ${Buffer.from('localAdmin:localAdmin').toString('base64')}` }

const random = (seed) => () => {
  seed |= 0
  seed = seed + 0x6D2B79F5 | 0
  let t = Math.imul(seed ^ seed >>> 15, 1 | seed)
  t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t
  return ((t ^ t >>> 14) >>> 0) / 4294967296
}
const WORDS = ['Alpha', 'Bravo', 'Charlie', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 'India', 'Juliet', 'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa', 'Quebec', 'Romeo', 'Sierra', 'Tango']
const mb = (bytes) => Math.round(bytes / 1024 / 1024 * 10) / 10
const round = (value, digits = 3) => Math.round(value * 10 ** digits) / 10 ** digits

const dirSize = (dir) => {
  let total = 0
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    total += entry.isDirectory() ? dirSize(full) : fs.statSync(full).size
  }
  return total
}

// ---------------------------------------------------------------------------------------------------------------------
// The child: one engine, one process
// ---------------------------------------------------------------------------------------------------------------------

/**
 * The options that point the CMS at an engine, what the server holds for the database of the run, and what to do when the
 * run is over (the two servers get a database of their own).
 * @param {string} engine
 * @returns {Promise<{dbEngine: object, serverBytes: function(): Promise<number>, teardown: function(): Promise<void>}>}
 */
async function prepareEngine (engine) {
  const database = `bench_${crypto.randomBytes(4).toString('hex')}`
  if (engine === 'mongodb') {
    const { MongoClient } = require('mongodb')
    const client = new MongoClient(`mongodb://${process.env.BENCH_MONGODB_URL}`, { serverSelectionTimeoutMS: 3000 })
    await client.connect()
    return {
      dbEngine: { type: 'mongodb', url: `${process.env.BENCH_MONGODB_URL}/${database}` },
      serverBytes: async () => {
        // a checkpoint first: dbStats reports the files on disk, which the last writes reach at the next checkpoint
        await client.db('admin').command({ fsync: 1 })
        const stats = await client.db(database).command({ dbStats: 1 })
        return stats.storageSize + stats.indexSize
      },
      teardown: async () => { await client.db(database).dropDatabase(); await client.close() }
    }
  }
  if (engine === 'postgres') {
    const { Client } = require('pg')
    const [host, port] = process.env.BENCH_POSTGRES_URL.split(':')
    const connection = { host, port: Number(port) || 5432, user: process.env.POSTGRES_USER, password: process.env.POSTGRES_PASSWORD, database: 'postgres' }
    const admin = new Client(connection)
    await admin.connect()
    await admin.query(`CREATE DATABASE "${database}"`)
    // the driver reads these when it is created
    Object.assign(process.env, { POSTGRES_HOST: host, POSTGRES_PORT: String(connection.port), POSTGRES_DB: database })
    return {
      dbEngine: { type: 'postgres', url: `${host}:${connection.port}/${database}` },
      serverBytes: async () => {
        // the tables of the run with their TOAST and indexes; pg_database_size would add the catalogs of the database
        const client = new Client({ ...connection, database })
        await client.connect()
        try {
          const { rows } = await client.query('SELECT COALESCE(SUM(pg_total_relation_size(oid)), 0) AS bytes FROM pg_class WHERE relkind IN (\'r\', \'m\') AND relnamespace = \'public\'::regnamespace')
          return Number(rows[0].bytes)
        } finally {
          await client.end()
        }
      },
      teardown: async () => { await admin.query(`DROP DATABASE IF EXISTS "${database}" WITH (FORCE)`); await admin.end() }
    }
  }
  return { dbEngine: { type: engine }, serverBytes: async () => 0, teardown: async () => {} }
}

// The HTTP client of the benchmark: keep-alive connections, shared by the clients of a phase. A machine that drops the first
// packet to a freshly opened local port (one Windows developer machine does, see docs/contributing/TESTING.md) answers a connection with
// ETIMEDOUT after 21 seconds: such a connection is given 2 seconds, then tried again, and the time it took is counted apart
// (`connectionRetries` and `retryMs` of the operation), so that a row carries the time of the answers, not of the machine.
const agent = new http.Agent({ keepAlive: true, maxSockets: 64 })
const CONNECT_TIMEOUT_MS = 2000
const RETRIED = ['ETIMEDOUT', 'ECONNRESET', 'ECONNREFUSED', 'EPIPE']
// the call of `measure` a request belongs to: where its retries are counted
const currentCall = new AsyncLocalStorage()

/**
 * One HTTP request, the whole answer read.
 * @param {string} url
 * @param {{method?: string, headers?: object, body?: Buffer|string}} [init]
 * @returns {Promise<{status: number, headers: object, body: Buffer}>}
 */
function requestOnce (url, { method = 'GET', headers = {}, body } = {}) {
  return new Promise((resolve, reject) => {
    const req = http.request(url, { method, headers: body ? { ...headers, 'Content-Length': Buffer.byteLength(body) } : headers, agent }, (res) => {
      const chunks = []
      res.on('data', chunk => chunks.push(chunk))
      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks) }))
      res.on('error', reject)
    })
    req.on('socket', (socket) => {
      if (socket.connecting) {
        const timer = setTimeout(() => req.destroy(Object.assign(new Error(`connect timeout after ${CONNECT_TIMEOUT_MS} ms`), { code: 'ETIMEDOUT' })), CONNECT_TIMEOUT_MS)
        socket.once('connect', () => clearTimeout(timer))
        socket.once('error', () => clearTimeout(timer))
      }
    })
    req.on('error', reject)
    req.end(body)
  })
}

/**
 * A request, tried again when the connection itself fails: up to ten times, with a growing pause, since the machine drops
 * the connections to a port for several seconds at a time. An HTTP answer, whatever its status, is returned as it is.
 * @param {string} url
 * @param {object} [init]
 * @returns {Promise<{status: number, headers: object, body: Buffer}>}
 */
async function request (url, init) {
  for (let attempt = 1; ; attempt++) {
    const started = performance.now()
    try {
      return await requestOnce(url, init)
    } catch (error) {
      if (attempt >= 10 || !RETRIED.includes(error.code)) {
        throw error
      }
      await new Promise(resolve => setTimeout(resolve, 250 * attempt))
      const call = currentCall.getStore()
      if (call) {
        call.retries++
        call.retryMs += performance.now() - started
      }
    }
  }
}

function makeRecord (index, next, uuid, now) {
  const words = () => `${WORDS[Math.floor(next() * WORDS.length)]} ${WORDS[Math.floor(next() * WORDS.length)]}`
  return {
    _id: uuid(),
    _createdAt: now,
    _updatedAt: now,
    _updatedBy: 'admins~localAdmin',
    sku: `SKU-${String(index).padStart(7, '0')}`,
    name: { enUS: `${words()} ${index}`, zhCN: `产品 ${index}` },
    description: { enUS: Array.from({ length: 40 }, () => WORDS[Math.floor(next() * WORDS.length)]).join(' ') },
    price: Math.round(next() * 100000) / 100,
    stock: Math.floor(next() * 1000),
    active: next() > 0.5,
    category: `category-${Math.floor(next() * 20)}`,
    released: now - Math.floor(next() * 1e10)
  }
}

/**
 * Runs `fn` `count` times, `concurrency` at a time, and reports the latency of one call and the throughput.
 * @param {function(number): Promise<*>} fn - given the number of the call
 * @param {number} count
 * @param {number} [concurrency]
 */
async function measure (fn, count, concurrency = 1) {
  count = Math.max(1, Math.round(count * SCALE))
  const times = []
  let failures = 0
  let next = 0
  let retries = 0
  let retryMs = 0
  const started = performance.now()
  await Promise.all(Array.from({ length: concurrency }, async () => {
    while (next < count) {
      const n = next++
      const call = { retries: 0, retryMs: 0 }
      const t0 = performance.now()
      try {
        await currentCall.run(call, () => fn(n))
      } catch (error) {
        failures++
        if (failures === 1) {
          console.error(`  first failure: ${error.message}`)
        }
      }
      // the time of the answer: a connection the machine dropped is not part of it
      times.push(performance.now() - t0 - call.retryMs)
      retries += call.retries
      retryMs += call.retryMs
    }
  }))
  // the clients worked side by side: the time they lost to dropped connections is shared between them
  const total = performance.now() - started - retryMs / concurrency
  times.sort((a, b) => a - b)
  const pick = (p) => times[Math.min(times.length - 1, Math.floor(times.length * p))]
  const result = { ms: round(times.reduce((a, b) => a + b, 0) / times.length), p50: round(pick(0.5)), p95: round(pick(0.95)), opsPerSecond: Math.round(count / (total / 1000)), count }
  if (failures) {
    result.failures = failures
  }
  if (retries) {
    result.connectionRetries = retries
    result.retryMs = Math.round(retryMs)
  }
  return result
}

async function runChild (engine) {
  process.env.LOG_LEVEL = process.env.LOG_LEVEL || 'error'
  const { startApp } = require('../helpers/app')
  const gc = () => global.gc && global.gc()
  const { dbEngine, serverBytes, teardown } = await prepareEngine(engine)
  const out = { engine, size: SIZE, scale: SCALE, node: process.version }
  const options = { resources: './test/bench/resources', dbEngine, security: { limits: { json: '1mb' } } }

  gc()
  const rssStart = process.memoryUsage().rss
  const app = await startApp(options, { keepData: true })
  // one address, not the two of `localhost` (a connection that fails is tried on each), and connections kept for the whole
  // run: the clients of a phase reuse the ones of the phase before instead of opening new ones
  app.url = `http://127.0.0.1:${app.server.address().port}`
  app.server.keepAliveTimeout = 10 * 60 * 1000
  const products = app.cms.resource('products')
  const json = (method, url, body) => request(`${app.url}${url}`, {
    method,
    headers: { ...AUTH, ...(body ? { 'Content-Type': 'application/json' } : {}) },
    body: body ? JSON.stringify(body) : undefined
  }).then((res) => {
    let data
    try {
      data = JSON.parse(res.body.toString('utf8'))
    } catch {}
    if (res.status >= 300) {
      throw new Error(`${method} ${url} answered ${res.status} ${JSON.stringify(data).slice(0, 120)}`)
    }
    return data
  })

  // the store is filled through the engine, in blocks: it is the state the operations are measured on, not what is measured
  const seedStarted = performance.now()
  const next = random(SIZE)
  const uuid = app.cms.options.uuid
  const now = 1700000000000
  const ids = []
  for (let from = 0; from < SIZE; from += 5000) {
    const operations = []
    for (let i = from; i < Math.min(SIZE, from + 5000); i++) {
      const record = makeRecord(i, next, uuid, now + i)
      ids.push(record._id)
      operations.push({ type: 'put', key: record._id, value: record })
    }
    await products.json._db.batch(operations)
  }
  if (products.json._db._persist) {
    await new Promise(resolve => setTimeout(resolve, 200))
    await products.json._db._persist()
  }
  out.seedMs = Math.round(performance.now() - seedStarted)
  gc()
  out.rssAfterSeedMb = mb(process.memoryUsage().rss - rssStart)

  const query = (q) => encodeURIComponent(JSON.stringify(q))
  const created = []
  const op = {}
  out.operations = op

  // warm up: the first requests load modules and open the connections
  for (let i = 0; i < 20; i++) {
    await json('GET', `/api/products/${ids[i % ids.length]}`)
  }

  console.error(`  [${engine}] writes`)
  op.create = await measure(async (i) => {
    const record = await json('POST', '/api/products', { sku: `NEW-${i}`, name: { enUS: `New ${i}` }, price: i, stock: i, category: `category-${i % 20}` })
    created.push(record._id)
  }, 200)
  op.update = await measure((i) => json('PUT', `/api/products/${created[i % created.length]}`, { stock: i + 1 }), 200)
  op.delete = await measure((i) => json('DELETE', `/api/products/${created[i]}`), Math.min(created.length, 200 * SCALE))
  op.create_8_parallel = await measure((i) => json('POST', '/api/products', { sku: `PAR-${i}`, name: { enUS: `Par ${i}` }, price: i, stock: i }), 400, 8)

  console.error(`  [${engine}] reads`)
  op.read_one = await measure((i) => json('GET', `/api/products/${ids[(i * 7919) % ids.length]}`), 1000)
  op.read_one_8_parallel = await measure((i) => json('GET', `/api/products/${ids[(i * 7919) % ids.length]}`), 2000, 8)
  op.list_page_50 = await measure((i) => json('GET', `/api/products?limit=50&page=${i % Math.max(1, Math.floor(SIZE / 50))}`), 100)
  op.list_1000 = await measure(() => json('GET', '/api/products?limit=1000'), 10)
  op.list_page_50_8_parallel = await measure((i) => json('GET', `/api/products?limit=50&page=${i % 20}`), 200, 8)

  console.error(`  [${engine}] searches`)
  const searches = Math.max(5, Math.round((SIZE > 50000 ? 5 : 20)))
  op.find_unique = await measure((i) => json('GET', `/api/products?query=${query({ sku: `SKU-${String((i * 7919) % SIZE).padStart(7, '0')}` })}`), searches)
  op.filter_equals = await measure(() => json('GET', `/api/products?limit=50&query=${query({ category: 'category-3' })}`), searches)
  op.filter_regex = await measure(() => json('GET', `/api/products?limit=50&query=${query({ 'name.enUS': { $regex: '^Alpha' } })}`), searches)
  op.filter_range = await measure(() => json('GET', `/api/products?limit=50&query=${query({ price: { $gte: 10, $lt: 50 } })}`), searches)

  console.error(`  [${engine}] files`)
  const record = await json('POST', '/api/products', { sku: 'WITH-FILES', name: { enUS: 'with files' } })
  const upload = async (field, name, type, bytes, recordId = record._id) => {
    // a multipart form with the file name field and the file, as a browser sends it
    const boundary = `----bench${crypto.randomBytes(12).toString('hex')}`
    const body = Buffer.concat([
      Buffer.from(`--${boundary}\r\nContent-Disposition: form-data; name="_filename"\r\n\r\n${name}\r\n--${boundary}\r\nContent-Disposition: form-data; name="${field}"; filename="${name}"\r\nContent-Type: ${type}\r\n\r\n`),
      bytes,
      Buffer.from(`\r\n--${boundary}--\r\n`)
    ])
    const res = await request(`${app.url}/api/products/${recordId}/attachments`, { method: 'POST', headers: { ...AUTH, 'Content-Type': `multipart/form-data; boundary=${boundary}` }, body })
    if (res.status >= 300) {
      throw new Error(`upload answered ${res.status} ${res.body.toString('utf8').slice(0, 120)}`)
    }
    return JSON.parse(res.body.toString('utf8'))
  }
  const small = crypto.randomBytes(100 * 1024)
  const large = crypto.randomBytes(5 * 1024 * 1024)
  const image = fs.readFileSync(path.join(__dirname, '..', 'fixtures', 'man.jpg'))
  const smallFiles = []
  const largeFiles = []
  const parallelFiles = []
  const images = []
  op.upload_file_100kb = await measure(async (i) => smallFiles.push(await upload('document', `small-${i}.bin`, 'application/octet-stream', small)), 40)
  op.upload_file_5mb = await measure(async (i) => largeFiles.push(await upload('document', `large-${i}.bin`, 'application/octet-stream', large)), 8)
  op.upload_file_100kb_4_parallel = await measure(async (i) => parallelFiles.push(await upload('document', `par-${i}.bin`, 'application/octet-stream', small)), 40, 4)
  // a field takes three images: every upload goes to a record of its own
  const imageRecords = await Promise.all(Array.from({ length: Math.max(1, Math.round(10 * SCALE)) }, (_, i) => json('POST', '/api/products', { sku: `IMG-${i}`, name: { enUS: `image ${i}` } })))
  op.upload_image = await measure(async (i) => images.push(await upload('photo', `man-${i}.jpg`, 'image/jpeg', image, imageRecords[i % imageRecords.length]._id)), 10)
  const attachmentUrl = (attachment) => `${app.url}/api/products/${record._id}/attachments/${attachment._id}`
  const download = async (attachment) => {
    const res = await request(attachmentUrl(attachment), { headers: AUTH })
    if (res.status >= 300) {
      throw new Error(`download answered ${res.status}`)
    }
  }
  op.download_file_100kb = await measure((i) => download(smallFiles[i % smallFiles.length]), 100)
  op.download_file_5mb = await measure((i) => download(largeFiles[i % largeFiles.length]), 10)
  op.remove_attachment = await measure(async (i) => {
    const res = await request(attachmentUrl(parallelFiles[i % parallelFiles.length]), { method: 'DELETE', headers: AUTH })
    // a file is removed once: a second call for the same one answers 404 and is not an operation of the engine
    if (res.status >= 300 && res.status !== 404) {
      throw new Error(`remove answered ${res.status}`)
    }
  }, 20)

  gc()
  out.rssAfterOperationsMb = mb(process.memoryUsage().rss - rssStart)
  await app.close()
  // the data folder holds the store of a local engine and the uploaded files of every engine; a server adds what it holds
  out.diskMb = mb(dirSize(app.dataDir) + (REMOTE.includes(engine) ? await serverBytes() : 0))

  // opening the store again: what a restart costs
  const reopenStarted = performance.now()
  const again = await startApp(options, { dataDir: app.dataDir, keepData: true })
  out.startMs = Math.round(performance.now() - reopenStarted)
  await again.close()
  // Windows holds a store file a moment after it is closed: a failed cleanup must not lose the result
  try {
    fs.rmSync(app.dataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 })
  } catch {}
  await teardown()
  return out
}

// ---------------------------------------------------------------------------------------------------------------------
// The parent: one child per engine, then the table
// ---------------------------------------------------------------------------------------------------------------------

const LABELS = {
  create: 'Create a record (POST)',
  update: 'Update a record (PUT)',
  delete: 'Delete a record (DELETE)',
  create_8_parallel: 'Create, 8 clients at once',
  read_one: 'Read one record by id',
  read_one_8_parallel: 'Read one record, 8 clients at once',
  list_page_50: 'List a page of 50',
  list_1000: 'List 1000 records',
  list_page_50_8_parallel: 'List a page of 50, 8 clients at once',
  find_unique: 'Find a record by its unique key',
  filter_equals: 'Filter, one field equals a value',
  filter_regex: 'Filter, text starts with',
  filter_range: 'Filter, number in a range',
  upload_file_100kb: 'Upload a 100 KB file',
  upload_file_5mb: 'Upload a 5 MB file',
  upload_file_100kb_4_parallel: 'Upload a 100 KB file, 4 clients at once',
  upload_image: 'Upload an image',
  download_file_100kb: 'Download a 100 KB file',
  download_file_5mb: 'Download a 5 MB file',
  remove_attachment: 'Remove a file'
}
const THROUGHPUT = (name) => /_(\d+)_parallel$/.test(name)

/**
 * One engine in a child process; a child that ends without a result (the machine refused the connections to its server
 * for too long) is started again, up to three times, on a fresh database each time.
 */
async function runEngine (engine) {
  for (let attempt = 1; ; attempt++) {
    try {
      return await runEngineOnce(engine)
    } catch (error) {
      if (attempt >= 3) {
        throw error
      }
      console.error(`  ${error.message}: starting ${engine} again`)
    }
  }
}

function runEngineOnce (engine) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, ['--expose-gc', '--no-deprecation', '--no-warnings', __filename, '--child', engine, '--size', String(SIZE), '--scale', String(SCALE)], { stdio: ['ignore', 'pipe', 'inherit'], env: process.env })
    let output = ''
    child.stdout.on('data', chunk => { output += chunk })
    child.on('close', (code) => {
      const line = output.trim().split('\n').pop()
      try {
        resolve(JSON.parse(line))
      } catch {
        reject(new Error(`${engine} exited with ${code} and no result`))
      }
    })
  })
}

/**
 * The results as a markdown table. Every value carries its unit: milliseconds for the time of one operation, operations per
 * second for the parallel ones, MB for memory and disk. The best of a row is in bold.
 */
function table (results) {
  const engines = results.map(result => result.engine)
  const best = (values, lower) => values.filter(v => v !== undefined).reduce((a, b) => (lower ? Math.min(a, b) : Math.max(a, b)), lower ? Infinity : -Infinity)
  const row = (label, values, lower, format) => {
    const top = best(values, lower)
    // one value in bold: the first of the best, if two are equal
    const winner = values.indexOf(top)
    return `| ${label} | ${values.map((value, i) => value === undefined ? 'N/A' : (i === winner ? `**${format(value)}**` : format(value))).join(' | ')} |`
  }
  const ms = (value) => `${value.toLocaleString('en')} ms`
  const megabytes = (value) => `${value.toLocaleString('en')} MB`
  const perSecond = (value) => `${value.toLocaleString('en')} ops/s`
  const lines = [`| ${(SIZE_FROM_REPORT || SIZE).toLocaleString('en')} records | ${engines.map(e => `\`${e}\``).join(' | ')} |`, `|---|${engines.map(() => '---').join('|')}|`]
  lines.push(row('Starting the server (reopening the store)', results.map(r => r.startMs), true, ms))
  lines.push(row('Memory after loading the records', results.map(r => r.rssAfterSeedMb), true, megabytes))
  lines.push(row('Memory after the operations', results.map(r => r.rssAfterOperationsMb), true, megabytes))
  lines.push(row('Disk space', results.map(r => r.diskMb), true, megabytes))
  for (const name of Object.keys(LABELS)) {
    const values = results.map(r => r.operations && r.operations[name])
    if (THROUGHPUT(name)) {
      lines.push(row(`${LABELS[name]} (higher is better)`, values.map(v => v && v.opsPerSecond), false, perSecond))
    } else {
      lines.push(row(LABELS[name], values.map(v => v && v.ms), true, ms))
    }
  }
  return lines.join('\n')
}

async function main () {
  const requested = option('engines')
  const engines = requested ? requested.split(',') : [...DEFAULT_ENGINES, ...(process.env.BENCH_MONGODB_URL ? ['mongodb'] : []), ...(process.env.BENCH_POSTGRES_URL ? ['postgres'] : [])]
  const results = []
  for (const engine of engines) {
    console.error(`--- ${engine}, ${SIZE} records`)
    const result = await runEngine(engine)
    for (const [name, value] of Object.entries(result.operations || {})) {
      if (value.failures) {
        console.error(`  ${name}: ${value.failures} of ${value.count} requests failed`)
      }
      if (value.connectionRetries) {
        console.error(`  ${name}: ${value.connectionRetries} connections dropped by the machine and tried again (${value.retryMs} ms, kept out of the figures)`)
      }
    }
    results.push(result)
  }
  const report = { node: process.version, cpus: os.cpus().length, platform: `${os.platform()} ${os.release()}`, size: SIZE, scale: SCALE, results }
  if (option('json')) {
    fs.writeFileSync(option('json'), JSON.stringify(report, null, 2))
  }
  const markdown = table(results)
  if (option('markdown')) {
    fs.writeFileSync(option('markdown'), markdown + '\n')
  }
  console.log(markdown)
  process.exit(0)
}

if (option('table')) {
  // print the table of a report written with --json again (after a change of the format)
  const report = JSON.parse(fs.readFileSync(option('table'), 'utf8'))
  SIZE_FROM_REPORT = report.size
  console.log(table(report.results))
} else if (option('child')) {
  runChild(option('child'))
    .then((result) => { process.stdout.write(`${JSON.stringify(result)}\n`); process.exit(0) })
    .catch((error) => { console.error(error); process.exit(1) })
} else {
  main().catch((error) => { console.error(error); process.exit(1) })
}
