import {
  mdiChevronDown,
  mdiMagnify,
  mdiMapMarker,
  mdiMapMarkerOutline,
  mdiNoteEditOutline,
  mdiNotePlusOutline,
  mdiCheckBold,
  mdiTrashCanOutline,
  mdiChevronLeft,
  mdiWeatherSunny,
  mdiWeatherNight,
  mdiDotsVertical,
  mdiCogOutline,
  mdiArrowUp,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiDragVertical,
  mdiSwapVertical,
  mdiLogout,
  mdiCrop,
  mdiFormatListChecks,
  mdiCloseCircleOutline,
  mdiClose,
  mdiInformation,
  mdiContentCopy,
  mdiContentSave,
  mdiCloudUpload,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatStrikethrough,
  mdiFormatParagraph,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatSuperscript,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatUnderline,
  mdiLink,
  mdiCodeTags,
  mdiFormatQuoteOpen,
  mdiXml,
  mdiFormatClear,
  mdiMinus,
  mdiArrowULeftTop,
  mdiArrowURightTop,
  mdiRefresh,
  mdiLockOutline,
  mdiAccountOutline,
  mdiAccountMultipleOutline,
  mdiEyeOutline,
  mdiLockOpenOutline,
  mdiWrap,
  mdiTarget,
  mdiFlagOutline,
  mdiAlertBoxOutline,
  mdiCursorText,
  mdiPackage,
  mdiMenu,
  mdiChevronRight,
  mdiAlertOutline,
  mdiInformationOutline,
  mdiUpload,
  mdiUnfoldMoreHorizontal,
  mdiUnfoldLessHorizontal,
  mdiSortVariant,
  mdiViewColumnOutline,
  mdiFormatLineSpacing,
  mdiTranslate,
  mdiImageOutline,
  mdiPaperclip,
  mdiCalendarBlankOutline,
  mdiClockOutline,
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
  mdiCheck,
  mdiChevronUp,
  mdiRotateLeft,
  mdiRotateRight,
  mdiFlipHorizontal,
  mdiFlipVertical,
  mdiMagnifyPlusOutline,
  mdiMagnifyMinusOutline,
  mdiAutoFix,
  mdiRestore,
  mdiCircleOutline,
  mdiSquareOutline,
  mdiPlus,
  mdiCursorDefaultOutline,
  mdiVectorPolygon,
  mdiVectorSquare,
  mdiStar,
  mdiStarOutline,
  mdiHeart,
  mdiHeartOutline,
  mdiThumbUp,
  mdiThumbUpOutline,
  mdiFire,
  mdiFlash,
  mdiFlashOutline,
  mdiCircle
} from '@mdi/js'
import { aliases } from 'vuetify/iconsets/mdi-svg'

// The icons the admin draws, by the name its templates give them ($information, icon="$magnify"): the ones Vuetify has by default, and the ones the admin adds.
// The app and the tests of the components both read them from here.
export const iconAliases = {
  ...aliases,
  chevronDown: mdiChevronDown,
  magnify: mdiMagnify,
  mapMarker: mdiMapMarker,
  mapMarkerOutline: mdiMapMarkerOutline,
  noteEditOutline: mdiNoteEditOutline,
  notePlusOutline: mdiNotePlusOutline,
  checkBold: mdiCheckBold,
  trashCanOutline: mdiTrashCanOutline,
  chevronLeft: mdiChevronLeft,
  weatherSunny: mdiWeatherSunny,
  weatherNight: mdiWeatherNight,
  dotsVertical: mdiDotsVertical,
  cogOutline: mdiCogOutline,
  arrowUp: mdiArrowUp,
  arrowDown: mdiArrowDown,
  arrowLeft: mdiArrowLeft,
  arrowRight: mdiArrowRight,
  dragVertical: mdiDragVertical,
  swapVertical: mdiSwapVertical,
  logout: mdiLogout,
  crop: mdiCrop,
  formatListChecks: mdiFormatListChecks,
  close: mdiClose,
  closeCircleOutline: mdiCloseCircleOutline,
  information: mdiInformation,
  contentCopy: mdiContentCopy,
  contentSave: mdiContentSave,
  cloudUpload: mdiCloudUpload,
  formatBold: mdiFormatBold,
  formatItalic: mdiFormatItalic,
  formatStrikethrough: mdiFormatStrikethrough,
  formatParagraph: mdiFormatParagraph,
  formatListBulleted: mdiFormatListBulleted,
  formatListNumbered: mdiFormatListNumbered,
  formatSuperscript: mdiFormatSuperscript,
  formatHeader1: mdiFormatHeader1,
  formatHeader2: mdiFormatHeader2,
  formatHeader3: mdiFormatHeader3,
  formatUnderline: mdiFormatUnderline,
  link: mdiLink,
  codeTags: mdiCodeTags,
  formatQuoteOpen: mdiFormatQuoteOpen,
  xml: mdiXml,
  formatClear: mdiFormatClear,
  minus: mdiMinus,
  arrowULeftTop: mdiArrowULeftTop,
  arrowURightTop: mdiArrowURightTop,
  refresh: mdiRefresh,
  lockOpenOutline: mdiLockOpenOutline,
  wrap: mdiWrap,
  lockOutline: mdiLockOutline,
  accountOutline: mdiAccountOutline,
  accountMultipleOutline: mdiAccountMultipleOutline,
  eyeOutline: mdiEyeOutline,
  target: mdiTarget,
  flagOutline: mdiFlagOutline,
  alertBoxOutline: mdiAlertBoxOutline,
  package: mdiPackage,
  menu: mdiMenu,
  chevronRight: mdiChevronRight,
  alertOutline: mdiAlertOutline,
  informationOutline: mdiInformationOutline,
  upload: mdiUpload,
  unfoldMore: mdiUnfoldMoreHorizontal,
  unfoldLess: mdiUnfoldLessHorizontal,
  sortVariant: mdiSortVariant,
  cursorText: mdiCursorText,
  viewColumn: mdiViewColumnOutline,
  formatLineSpacing: mdiFormatLineSpacing,
  translate: mdiTranslate,
  imageOutline: mdiImageOutline,
  paperclip: mdiPaperclip,
  calendarBlankOutline: mdiCalendarBlankOutline,
  clockOutline: mdiClockOutline,
  chevronDoubleLeft: mdiChevronDoubleLeft,
  chevronDoubleRight: mdiChevronDoubleRight,
  check: mdiCheck,
  chevronUp: mdiChevronUp,
  rotateLeft: mdiRotateLeft,
  rotateRight: mdiRotateRight,
  flipHorizontal: mdiFlipHorizontal,
  flipVertical: mdiFlipVertical,
  magnifyPlusOutline: mdiMagnifyPlusOutline,
  magnifyMinusOutline: mdiMagnifyMinusOutline,
  autoFix: mdiAutoFix,
  restore: mdiRestore,
  circleOutline: mdiCircleOutline,
  squareOutline: mdiSquareOutline,
  plus: mdiPlus,
  cursorDefaultOutline: mdiCursorDefaultOutline,
  vectorPolygon: mdiVectorPolygon,
  vectorSquare: mdiVectorSquare,
  star: mdiStar,
  starOutline: mdiStarOutline,
  heart: mdiHeart,
  heartOutline: mdiHeartOutline,
  thumbUp: mdiThumbUp,
  thumbUpOutline: mdiThumbUpOutline,
  fire: mdiFire,
  flash: mdiFlash,
  flashOutline: mdiFlashOutline,
  circle: mdiCircle
}
