import {
  mdiChevronDown,
  mdiMagnify,
  mdiNoteEditOutline,
  mdiNotePlusOutline,
  mdiCheckBold,
  mdiTrashCanOutline,
  mdiChevronLeft,
  mdiWeatherSunny,
  mdiWeatherNight,
  mdiDotsVertical,
  mdiCogOutline,
  mdiArrowUp,
  mdiArrowDown,
  mdiLogout,
  mdiCrop,
  mdiFormatListChecks,
  mdiCloseCircleOutline,
  mdiClose,
  mdiInformation,
  mdiContentCopy,
  mdiContentSave,
  mdiCloudUpload,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatStrikethrough,
  mdiFormatParagraph,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatSuperscript,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatUnderline,
  mdiLink,
  mdiFormatQuoteOpen,
  mdiXml,
  mdiFormatClear,
  mdiMinus,
  mdiArrowULeftTop,
  mdiArrowURightTop,
  mdiRefresh,
  mdiLockOutline,
  mdiLockOpenOutline,
  mdiWrap,
  mdiTarget,
  mdiFlagOutline,
  mdiAlertBoxOutline,
  mdiCursorText,
  mdiPackage,
  mdiMenu,
  mdiChevronRight,
  mdiAlertOutline,
  mdiInformationOutline,
  mdiUpload,
  mdiUnfoldMoreHorizontal,
  mdiUnfoldLessHorizontal,
  mdiSortVariant,
  mdiViewColumnOutline,
  mdiFormatLineSpacing,
  mdiTranslate,
  mdiImageOutline,
  mdiPaperclip,
  mdiCalendarBlankOutline,
  mdiClockOutline,
  mdiChevronDoubleLeft,
  mdiChevronDoubleRight,
  mdiCheck,
  mdiChevronUp
} from '@mdi/js'
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import 'vuetify/styles'

/*
 * Vuetify palette. Keep in sync with src/styles/tokens.css (which is the source
 * of truth for the hand written CSS). Every foreground/background pair here
 * meets WCAG AA. Custom keys are exposed as --v-theme-<name> and as
 * `bg-<name>` / `text-<name>` utility classes.
 */
const lightColors = {
  background: '#EEF0F5',
  surface: '#FFFFFF',
  'surface-bright': '#FFFFFF',
  'surface-light': '#F4F5F9',
  'surface-variant': '#1E2330', // used by Vuetify for tooltips (inverse surface)
  'on-surface-variant': '#FFFFFF',
  primary: '#3846C7',
  'primary-darken-1': '#2D3AA8',
  secondary: '#3846C7',
  'secondary-darken-1': '#2D3AA8',
  error: '#A8362F',
  info: '#2C5DA3',
  success: '#2D6B52',
  warning: '#85560A',
  'on-primary': '#FFFFFF',
  'on-secondary': '#FFFFFF',
  'on-error': '#FFFFFF',
  'on-info': '#FFFFFF',
  'on-success': '#FFFFFF',
  'on-warning': '#FFFFFF',
  'on-background': '#161B26',
  'on-surface': '#161B26',
  'surface-2': '#F4F5F9',
  'primary-soft': '#EDEFFA',
  'on-primary-soft': '#252F9A'
}

const darkColors = {
  background: '#0F1116',
  surface: '#171A21',
  'surface-bright': '#292E3A',
  'surface-light': '#1F232C',
  'surface-variant': '#E3E6F6',
  'on-surface-variant': '#161A2E',
  primary: '#9AA6FF',
  'primary-darken-1': '#B3BCFF',
  secondary: '#9AA6FF',
  'secondary-darken-1': '#B3BCFF',
  error: '#F09A93',
  info: '#8DB4F0',
  success: '#7BCBA5',
  warning: '#E6B565',
  'on-primary': '#0B1033',
  'on-secondary': '#062B28',
  'on-error': '#3A0A07',
  'on-info': '#06213F',
  'on-success': '#052B1D',
  'on-warning': '#2E1A00',
  'on-background': '#E8EAF6',
  'on-surface': '#E8EAF6',
  'surface-2': '#1F232C',
  'primary-soft': '#232842',
  'on-primary-soft': '#D6DBFF'
}

const vuetify = createVuetify({
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        dark: false,
        colors: lightColors,
        variables: {
          'border-color': '#6B7290',
          'border-opacity': 0.5,
          'high-emphasis-opacity': 0.92,
          'medium-emphasis-opacity': 0.72,
          'disabled-opacity': 0.42,
          'focus-opacity': 0.12,
          'hover-opacity': 0.06
        }
      },
      dark: {
        dark: true,
        colors: darkColors,
        variables: {
          'border-color': '#8089A0',
          'border-opacity': 0.5,
          'high-emphasis-opacity': 0.94,
          'medium-emphasis-opacity': 0.74,
          'disabled-opacity': 0.42,
          'focus-opacity': 0.16,
          'hover-opacity': 0.1
        }
      }
    }
  },
  defaults: {
    VBtn: { elevation: 0 },
    VCard: { elevation: 0 },
    VTooltip: { openDelay: 300 },
    VMenu: { transition: 'fade-transition', offset: 6 },
    VSelect: { menuProps: { offset: 6, maxHeight: 320, transition: 'fade-transition' }, menuIcon: '$chevronDown' },
    VAutocomplete: { menuProps: { offset: 6, maxHeight: 320, transition: 'fade-transition' }, menuIcon: '$chevronDown' },
    VCombobox: { menuProps: { offset: 6, maxHeight: 320, transition: 'fade-transition' }, menuIcon: '$chevronDown' },
    VChip: { size: 'default' }
  },
  icons: {
    defaultSet: 'mdi',
    aliases: {
      ...aliases,
      chevronDown: mdiChevronDown,
      magnify: mdiMagnify,
      noteEditOutline: mdiNoteEditOutline,
      notePlusOutline: mdiNotePlusOutline,
      checkBold: mdiCheckBold,
      trashCanOutline: mdiTrashCanOutline,
      chevronLeft: mdiChevronLeft,
      weatherSunny: mdiWeatherSunny,
      weatherNight: mdiWeatherNight,
      dotsVertical: mdiDotsVertical,
      cogOutline: mdiCogOutline,
      arrowUp: mdiArrowUp,
      arrowDown: mdiArrowDown,
      logout: mdiLogout,
      crop: mdiCrop,
      formatListChecks: mdiFormatListChecks,
      close: mdiClose,
      closeCircleOutline: mdiCloseCircleOutline,
      information: mdiInformation,
      contentCopy: mdiContentCopy,
      contentSave: mdiContentSave,
      cloudUpload: mdiCloudUpload,
      formatBold: mdiFormatBold,
      formatItalic: mdiFormatItalic,
      formatStrikethrough: mdiFormatStrikethrough,
      formatParagraph: mdiFormatParagraph,
      formatListBulleted: mdiFormatListBulleted,
      formatListNumbered: mdiFormatListNumbered,
      formatSuperscript: mdiFormatSuperscript,
      formatHeader1: mdiFormatHeader1,
      formatHeader2: mdiFormatHeader2,
      formatHeader3: mdiFormatHeader3,
      formatUnderline: mdiFormatUnderline,
      link: mdiLink,
      formatQuoteOpen: mdiFormatQuoteOpen,
      xml: mdiXml,
      formatClear: mdiFormatClear,
      minus: mdiMinus,
      arrowULeftTop: mdiArrowULeftTop,
      arrowURightTop: mdiArrowURightTop,
      refresh: mdiRefresh,
      lockOpenOutline: mdiLockOpenOutline,
      wrap: mdiWrap,
      lockOutline: mdiLockOutline,
      target: mdiTarget,
      flagOutline: mdiFlagOutline,
      alertBoxOutline: mdiAlertBoxOutline,
      package: mdiPackage,
      menu: mdiMenu,
      chevronRight: mdiChevronRight,
      alertOutline: mdiAlertOutline,
      informationOutline: mdiInformationOutline,
      upload: mdiUpload,
      unfoldMore: mdiUnfoldMoreHorizontal,
      unfoldLess: mdiUnfoldLessHorizontal,
      sortVariant: mdiSortVariant,
      cursorText: mdiCursorText,
      viewColumn: mdiViewColumnOutline,
      formatLineSpacing: mdiFormatLineSpacing,
      translate: mdiTranslate,
      imageOutline: mdiImageOutline,
      paperclip: mdiPaperclip,
      calendarBlankOutline: mdiCalendarBlankOutline,
      clockOutline: mdiClockOutline,
      chevronDoubleLeft: mdiChevronDoubleLeft,
      chevronDoubleRight: mdiChevronDoubleRight,
      check: mdiCheck,
      chevronUp: mdiChevronUp
    },
    sets: {
      mdi
    }
  }
})

export default vuetify
